---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo
  namespace: pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-demo
  template:
    metadata:
      labels:
        app: k8s-demo
        version: 0.0.0.1
    spec:
      containers:
      - name: k8s-demo
        image: 192.168.0.201:80/pro/k8s-demo:0.0.0.1
        ports:
        - containerPort: 8001
          protocol: TCP
        env:
        - name: APP_RUN
          value: "java -XX:+UseG1GC -Xmx600m -Xms32m -Djava.security.egd=file:/dev/./urandom -jar /app.jar"
        - name: logging_path
          value: "/logs/${HOSTNAME}"
      imagePullPolicy: Always
      imagePullSecrets:
      - name: registry-secret

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-demo
  namespace: pro
spec:
  ports:
  - port: 8001
    targetPort: 8001
  selector:
    app: k8s-demo